enc:
  size: [ 10000, 10000 ]
  center: [186076, 7098000]
  depths: [ 0, 1, 2, 5, 10, 20, 50, 100, 200, 350, 500 ]
  crs: "UTM33N"
  resources: [ "data/db/" ]

display:
  colorbar: False
  dark_mode: True
  fullscreen: False
  resolution: 720
  anchor: "center"
  dpi: 96
