enc:
  size: [ 40000, 40000 ]
  center: [134675, 7005883] #[222016, 7067340] # [ 239601, 7068072 ]
  depths: [ 0, 1, 2, 5, 10, 20, 50, 100, 200, 350, 500 ]
  crs: "UTM33N"
  resources: [ "data/db/" ]

display:
  colorbar: False
  dark_mode: True
  fullscreen: False
  resolution: 720
  anchor: "center"
  dpi: 96
